### ISSUE TITLE
config: map - add type checking for repository instance

### ISSUE THREAD

**Issue by castamir** [Joseki/LeanMapper-extension#8]
``` yaml
LeanMapper:
    map:
        my_client: Project\Client
```

vs

``` yaml
LeanMapper:
    map:
        my_client: Project\ClientRepository
```
